/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capstone_project_management_system;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Edris
 */
public class Add_Capstone extends javax.swing.JFrame {

    /**
     * Creates new form Add_Capstone
     */
    Connection con = null;
    Statement state = null;
    ResultSet rs;
    public Add_Capstone() {
        initComponents();
        list_users();
        list_course();
        
    }
    
    public void list_users()
    {
        try
        {
            con = dbConnect.connect();
            
            String query = "select * from user";
            state = con.createStatement();
            rs = state.executeQuery(query);
            
            while(rs.next())
            {
                String midname = rs.getString("Mid_name");
                
                ass_user.addItem(rs.getString("First_name") +" "+midname.charAt(0)+". "+ rs.getString("Last_Name"));
            }
        }catch(Exception e)
        {
            
        }
    }
    public void list_course()
    {
        try
        {
            con = dbConnect.connect();
            
            String query = "select * from course";
            state = con.createStatement();
            rs = state.executeQuery(query);
            
            while(rs.next())
            {
                course.addItem(rs.getString("course_name"));
            }
        }
        catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ass_user = new javax.swing.JComboBox<>();
        course = new javax.swing.JComboBox<>();
        school = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        school1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setText("ADD CAPSTONE:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 60, 110, 23);

        jLabel2.setText("ASSIGNED RESEARCH ADVISER:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 170, 200, 23);

        jLabel3.setText("YEAR TO:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 100, 90, 23);

        jLabel4.setText("COURSE:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 240, 83, 23);

        ass_user.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select" }));
        jPanel1.add(ass_user);
        ass_user.setBounds(40, 200, 210, 24);

        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please Select" }));
        jPanel1.add(course);
        course.setBounds(40, 270, 300, 24);

        school.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolActionPerformed(evt);
            }
        });
        school.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                schoolKeyPressed(evt);
            }
        });
        jPanel1.add(school);
        school.setBounds(230, 130, 70, 30);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(80, 340, 190, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-arrow-52.png"))); // NOI18N
        jLabel5.setText(" BACK");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 10, 100, 40);

        jLabel6.setText("SCHOOL YEAR:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 100, 90, 23);

        school1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                school1ActionPerformed(evt);
            }
        });
        school1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                school1KeyPressed(evt);
            }
        });
        jPanel1.add(school1);
        school1.setBounds(120, 130, 70, 30);

        jLabel7.setText("YEAR FROM:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(120, 100, 90, 23);

        jLabel8.setText("-");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 130, 10, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void schoolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_schoolKeyPressed
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c) || c == KeyEvent.VK_MINUS){
           
                school.setEditable(true);
                
        }else{
            school.setEditable(false);
        }
    }//GEN-LAST:event_schoolKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int select = ass_user.getSelectedIndex();
        try
        {
            con = dbConnect.connect();
            
            String query = "insert into capstone values(NULL, ?,'"+select+"','"+course.getSelectedIndex()+"')";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, school1.getText() +" - "+ school.getText());
            ps.execute();
            
            Show_user Show_user = new Show_user();
            Show_user.setVisible(true);
            this.dispose();
            JOptionPane.showMessageDialog(null, "success");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Show_user Show_user = new Show_user();
        Show_user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void school1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_school1KeyPressed
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c) || c == KeyEvent.VK_MINUS){
           
                school.setEditable(true);
                
        }else{
            school.setEditable(false);
        }
    }//GEN-LAST:event_school1KeyPressed

    private void school1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_school1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_school1ActionPerformed

    private void schoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Capstone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Capstone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Capstone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Capstone.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Capstone().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ass_user;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField school;
    private javax.swing.JTextField school1;
    // End of variables declaration//GEN-END:variables
}
