/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capstone_project_management_system;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Edris
 */
public class Add_Book extends javax.swing.JFrame {

    /**
     * Creates new form Add_Book
     */
    Connection con = null;
    Statement state = null;
    ResultSet rs, rs1;
    String course_get, cap_no;
    String filename, filename1, filename2, filename3, filename4, filename5, filename6, filename7;
    public Add_Book() {
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        initComponents();
        jLabel64.setVisible(false);
        jLabel6.setVisible(false);
        jLabel13.setVisible(false);
        jLabel20.setVisible(false);
        
        User_Dashboard User_Dashboard = new User_Dashboard();
        course_get = User_Dashboard.g_course;
        show_course();
        
        cap_no = User_Dashboard.g_capstone_no;
    }
    public void show_course()
    {
        try
        {
            con = dbConnect.connect();
            String query = "select course_name from course where course_no = '"+course_get+"'";
            state = con.createStatement();
            rs = state.executeQuery(query);
            
            while(rs.next())
            {
                String N_course = rs.getString("course_name");
                jLabel10.setText(N_course);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sex1 = new javax.swing.ButtonGroup();
        sex2 = new javax.swing.ButtonGroup();
        sex3 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jTextField27 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-back-arrow-52.png"))); // NOI18N
        jLabel17.setText(" BACK");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel17);
        jLabel17.setBounds(20, 30, 97, 40);

        jLabel10.setFont(new java.awt.Font("ADAM.CG PRO", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("ADD BOOK");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(240, 80, 1090, 50);

        jButton10.setText("SAVE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(160, 610, 320, 40);

        jButton9.setText("Choose");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9);
        jButton9.setBounds(230, 500, 90, 25);
        jPanel2.add(jLabel64);
        jLabel64.setBounds(130, 270, 300, 200);

        jButton2.setText("Choose");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(950, 250, 80, 25);

        jButton3.setText("Choose");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(1180, 250, 80, 25);

        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(710, 250, 90, 25);

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jLabel20);
        jLabel20.setBounds(1070, 220, 80, 70);

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("First name:");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(1070, 310, 80, 15);

        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField12);
        jTextField12.setBounds(1160, 310, 100, 30);

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Middle name:");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(1070, 370, 90, 15);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Last name:");
        jPanel2.add(jLabel23);
        jLabel23.setBounds(1070, 340, 80, 15);

        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField13KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField13KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField13);
        jTextField13.setBounds(1160, 340, 100, 30);

        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField14KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField14KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField14);
        jTextField14.setBounds(1160, 370, 100, 30);

        jTextField16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField16KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField16);
        jTextField16.setBounds(1160, 400, 100, 30);

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Age:");
        jPanel2.add(jLabel25);
        jLabel25.setBounds(1070, 400, 60, 15);

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Gender:");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(1070, 430, 60, 15);

        sex3.add(jRadioButton5);
        jRadioButton5.setText("Male");
        jPanel2.add(jRadioButton5);
        jRadioButton5.setBounds(1090, 450, 60, 23);

        sex3.add(jRadioButton6);
        jRadioButton6.setText("Female");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton6);
        jRadioButton6.setBounds(1090, 480, 80, 23);

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jLabel13);
        jLabel13.setBounds(840, 220, 80, 70);

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("First name:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(840, 310, 80, 15);

        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField7KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField7);
        jTextField7.setBounds(930, 310, 100, 30);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Middle name:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(840, 370, 90, 15);

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Last name:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(840, 340, 80, 15);

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField8KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField8);
        jTextField8.setBounds(930, 340, 100, 30);

        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField9KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField9);
        jTextField9.setBounds(930, 370, 100, 30);

        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField11);
        jTextField11.setBounds(930, 400, 100, 30);

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Age:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(840, 400, 60, 15);

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Gender:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(840, 430, 60, 15);

        sex2.add(jRadioButton3);
        jRadioButton3.setText("Male");
        jPanel2.add(jRadioButton3);
        jRadioButton3.setBounds(860, 450, 60, 23);

        sex2.add(jRadioButton4);
        jRadioButton4.setText("Female");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton4);
        jRadioButton4.setBounds(860, 480, 80, 23);

        sex1.add(jRadioButton1);
        jRadioButton1.setText("Male");
        jPanel2.add(jRadioButton1);
        jRadioButton1.setBounds(620, 450, 60, 23);

        sex1.add(jRadioButton2);
        jRadioButton2.setText("Female");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(620, 480, 80, 23);

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField2KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(690, 310, 100, 30);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField3);
        jTextField3.setBounds(690, 340, 100, 30);

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField4);
        jTextField4.setBounds(690, 370, 100, 30);

        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField6);
        jTextField6.setBounds(690, 400, 100, 30);

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Gender:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(600, 430, 60, 15);

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Age:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(600, 400, 60, 15);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Last name:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(600, 340, 80, 15);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Middle name:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(600, 370, 90, 15);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("First name:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(600, 310, 80, 15);

        jLabel29.setFont(new java.awt.Font("ADAM.CG PRO", 1, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("ADD BOOK");
        jPanel2.add(jLabel29);
        jLabel29.setBounds(-650, 200, 200, 50);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(600, 220, 80, 70);

        jLabel1.setFont(new java.awt.Font("ADAM.CG PRO", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ADD BOOK");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 80, 200, 50);

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(160, 150, 380, 30);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Title:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 150, 50, 19);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextArea1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(160, 200, 380, 60);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Description:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(60, 200, 80, 19);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Authors:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(560, 200, 60, 19);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/oki5.jpg"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 1380, 670);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);
        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 670, 1370, 50);

        jLabel43.setBackground(new java.awt.Color(0, 0, 0));
        jLabel43.setForeground(new java.awt.Color(0, 0, 0));
        jLabel43.setText("asd");
        jPanel2.add(jLabel43);
        jLabel43.setBounds(230, 390, 90, 90);

        jButton6.setText("Choose");
        jPanel2.add(jButton6);
        jButton6.setBounds(330, 430, 71, 25);

        jLabel44.setForeground(new java.awt.Color(0, 0, 0));
        jLabel44.setText("First name:");
        jPanel2.add(jLabel44);
        jLabel44.setBounds(230, 480, 80, 15);
        jPanel2.add(jTextField27);
        jTextField27.setBounds(300, 480, 100, 19);

        jLabel45.setForeground(new java.awt.Color(0, 0, 0));
        jLabel45.setText("Last name:");
        jPanel2.add(jLabel45);
        jLabel45.setBounds(230, 510, 80, 15);

        jLabel46.setForeground(new java.awt.Color(0, 0, 0));
        jLabel46.setText("Middle name:");
        jPanel2.add(jLabel46);
        jLabel46.setBounds(230, 540, 90, 15);
        jPanel2.add(jTextField28);
        jTextField28.setBounds(300, 540, 100, 19);

        jLabel47.setForeground(new java.awt.Color(0, 0, 0));
        jLabel47.setText("Address:");
        jPanel2.add(jLabel47);
        jLabel47.setBounds(230, 570, 80, 15);
        jPanel2.add(jTextField29);
        jTextField29.setBounds(300, 570, 100, 19);

        jLabel48.setForeground(new java.awt.Color(0, 0, 0));
        jLabel48.setText("Age:");
        jPanel2.add(jLabel48);
        jLabel48.setBounds(230, 600, 60, 15);
        jPanel2.add(jTextField30);
        jTextField30.setBounds(300, 600, 100, 19);

        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Gender:");
        jPanel2.add(jLabel49);
        jLabel49.setBounds(230, 630, 60, 15);

        jRadioButton11.setText("Male");
        jPanel2.add(jRadioButton11);
        jRadioButton11.setBounds(250, 650, 50, 23);

        jRadioButton12.setText("Female");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton12);
        jRadioButton12.setBounds(250, 680, 80, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            filename = f.getAbsolutePath();
            //jTextField1.setText(f.getAbsolutePath());
            Image getAbsolutePath = null;
            ImageIcon icon = new ImageIcon(f.getAbsolutePath());
            Image image = icon.getImage().getScaledInstance(jLabel6.getWidth(), jLabel6.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledImg = new ImageIcon(image);
            jLabel6.setIcon(scaledImg);
            jLabel6.setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please choose an image!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try
        {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            filename1 = f.getAbsolutePath();
            //jTextField1.setText(f.getAbsolutePath());
            Image getAbsolutePath = null;
            ImageIcon icon = new ImageIcon(f.getAbsolutePath());
            Image image = icon.getImage().getScaledInstance(jLabel13.getWidth(), jLabel13.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledImg = new ImageIcon(image);
            jLabel13.setIcon(scaledImg);
            jLabel13.setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please choose an image!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try
        {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            filename2 = f.getAbsolutePath();
            //jTextField1.setText(f.getAbsolutePath());
            Image getAbsolutePath = null;
            ImageIcon icon = new ImageIcon(f.getAbsolutePath());
            Image image = icon.getImage().getScaledInstance(jLabel20.getWidth(), jLabel20.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledImg = new ImageIcon(image);
            jLabel20.setIcon(scaledImg);
            jLabel20.setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please choose an image!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try
        {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File f = chooser.getSelectedFile();
            filename7 = f.getAbsolutePath();
            //jTextField1.setText(f.getAbsolutePath());
            Image getAbsolutePath = null;
            ImageIcon icon = new ImageIcon(f.getAbsolutePath());
            Image image = icon.getImage().getScaledInstance(jLabel64.getWidth(), jLabel64.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledImg = new ImageIcon(image);
            jLabel64.setIcon(scaledImg);
            jLabel64.setVisible(true);
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please choose an image!");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyReleased
        try
        {
            int pos = jTextField2.getCaretPosition();

            jTextField2.setCaretPosition(pos);
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jTextField2KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        try
        {
            int pos = jTextField3.getCaretPosition();

            jTextField3.setCaretPosition(pos);
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        try
        {
            int pos = jTextField4.getCaretPosition();

            jTextField4.setCaretPosition(pos);
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyReleased
        try
        {
            int pos = jTextField7.getCaretPosition();

            jTextField7.setCaretPosition(pos);
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jTextField7KeyReleased

    private void jTextField8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyReleased
        try
        {
            int pos = jTextField8.getCaretPosition();

            jTextField8.setCaretPosition(pos);
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jTextField8KeyReleased

    private void jTextField9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyReleased
        try
        {
            int pos = jTextField9.getCaretPosition();

            jTextField9.setCaretPosition(pos);
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jTextField9KeyReleased

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
        try
        {
            int pos = jTextField12.getCaretPosition();

            jTextField12.setCaretPosition(pos);
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jTextField12KeyReleased

    private void jTextField13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyReleased
        try
        {
            int pos = jTextField13.getCaretPosition();

            jTextField13.setCaretPosition(pos);
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jTextField13KeyReleased

    private void jTextField14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyReleased
        try
        {
            int pos = jTextField4.getCaretPosition();

            jTextField4.setCaretPosition(pos);
        }
        catch(Exception e)
        {

        }
    }//GEN-LAST:event_jTextField14KeyReleased

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) || Character.isSpace(c) || c == KeyEvent.VK_SHIFT){
            jTextField2.setEditable(true);
            
        }else{
            jTextField2.setEditable(false);
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) || Character.isSpace(c) || c == KeyEvent.VK_SHIFT){
            jTextField3.setEditable(true);
            
        }else{
            jTextField3.setEditable(false);
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) || Character.isSpace(c) || c == KeyEvent.VK_SHIFT){
            jTextField4.setEditable(true);
            
        }else{
            jTextField4.setEditable(false);
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) || Character.isSpace(c) || c == KeyEvent.VK_SHIFT){
            jTextField7.setEditable(true);
            
        }else{
            jTextField7.setEditable(false);
        }
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) || Character.isSpace(c) || c == KeyEvent.VK_SHIFT){
            jTextField8.setEditable(true);
            
        }else{
            jTextField8.setEditable(false);
        }
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) || Character.isSpace(c) || c == KeyEvent.VK_SHIFT){
            jTextField9.setEditable(true);
            
        }else{
            jTextField9.setEditable(false);
        }
    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) || Character.isSpace(c) || c == KeyEvent.VK_SHIFT){
            jTextField12.setEditable(true);
            
        }else{
            jTextField12.setEditable(false);
        }
    }//GEN-LAST:event_jTextField12KeyPressed

    private void jTextField13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) || Character.isSpace(c) || c == KeyEvent.VK_SHIFT){
            jTextField13.setEditable(true);
            
        }else{
            jTextField13.setEditable(false);
        }
    }//GEN-LAST:event_jTextField13KeyPressed

    private void jTextField14KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyPressed
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isISOControl(c) || Character.isSpace(c) || c == KeyEvent.VK_SHIFT){
            jTextField14.setEditable(true);
            
        }else{
            jTextField14.setEditable(false);
        }
    }//GEN-LAST:event_jTextField14KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
                if(jTextField6.getText().length()<3 || Character.isISOControl(c)){
                   jTextField6.setEditable(true);
                }else{
                   jTextField6.setEditable(false);
                }
        }else{
            jTextField6.setEditable(false);
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
                if(jTextField11.getText().length()<3 || Character.isISOControl(c)){
                   jTextField11.setEditable(true);
                }else{
                   jTextField11.setEditable(false);
                }
        }else{
            jTextField11.setEditable(false);
        }
    }//GEN-LAST:event_jTextField11KeyPressed

    private void jTextField16KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField16KeyPressed
        char c = evt.getKeyChar();
        if(Character.isDigit(c) || Character.isISOControl(c)){
                if(jTextField16.getText().length()<3 || Character.isISOControl(c)){
                   jTextField16.setEditable(true);
                }else{
                   jTextField16.setEditable(false);
                }
        }else{
            jTextField16.setEditable(false);
        }
    }//GEN-LAST:event_jTextField16KeyPressed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        jRadioButton1.setActionCommand("Male");
        jRadioButton2.setActionCommand("Female");
        
        jRadioButton3.setActionCommand("Male");
        jRadioButton4.setActionCommand("Female");
        
        jRadioButton5.setActionCommand("Male");
        jRadioButton6.setActionCommand("Female");
        
        if(jTextField1.getText().isEmpty() 
                && jTextArea1.getText().isEmpty()
                && jLabel64.isVisible() == false
                && jLabel6.isVisible() == false
                && jLabel13.isVisible() == false
                && jLabel20.isVisible() == false
                && jTextField2.getText().isEmpty()
                && jTextField3.getText().isEmpty()
                && jTextField4.getText().isEmpty()
                && jTextField6.getText().isEmpty()
                && jTextField7.getText().isEmpty()
                && jTextField8.getText().isEmpty()
                && jTextField9.getText().isEmpty()
                && jTextField11.getText().isEmpty()
                && jTextField12.getText().isEmpty()
                && jTextField13.getText().isEmpty()
                && jTextField14.getText().isEmpty()
                && jTextField16.getText().isEmpty()
                && sex1.isSelected(null)
                && sex2.isSelected(null)
                && sex3.isSelected(null))
        {
            JOptionPane.showMessageDialog(null, "Please Fill ALL Fields!!!", "",JOptionPane.ERROR_MESSAGE);
        }
        else if(jTextField1.getText().isEmpty() 
                || jTextArea1.getText().isEmpty()
                || jLabel64.isVisible() == false
                || jLabel6.isVisible() == false
                || jLabel13.isVisible() == false
                || jLabel20.isVisible() == false
                || jTextField2.getText().isEmpty()
                || jTextField3.getText().isEmpty()
                || jTextField4.getText().isEmpty()
                || jTextField6.getText().isEmpty()
                || jTextField7.getText().isEmpty()
                || jTextField8.getText().isEmpty()
                || jTextField9.getText().isEmpty()
                || jTextField11.getText().isEmpty()
                || jTextField12.getText().isEmpty()
                || jTextField13.getText().isEmpty()
                || jTextField14.getText().isEmpty()
                || jTextField16.getText().isEmpty()
                || sex1.isSelected(null)
                || sex2.isSelected(null))
        {
            JOptionPane.showMessageDialog(null, "Some fields are not FILLED!!", "",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try
            {
                con = dbConnect.connect();
                String query = "insert into book values(null, '"+jTextField1.getText()+"', '"+jTextArea1.getText()+"', '"+filename7+"', (select capstone_no from capstone where capstone_no = '"+cap_no+"'))";
                String query2 = "insert into students values (null,'"+filename+"', '"+jTextField2.getText()+"', '"+jTextField4.getText()+"', '"+jTextField3.getText()+"', '"+jTextField6.getText()+"', '"+sex1.getSelection().getActionCommand()+"', (select max(book_id) from book))";
                String query3 = "insert into students values (null,'"+filename1+"', '"+jTextField7.getText()+"', '"+jTextField9.getText()+"', '"+jTextField8.getText()+"', '"+jTextField11.getText()+"', '"+sex2.getSelection().getActionCommand()+"', (select max(book_id) from book))";
                String query4 = "insert into students values (null,'"+filename2+"', '"+jTextField12.getText()+"', '"+jTextField14.getText()+"', '"+jTextField13.getText()+"', '"+jTextField16.getText()+"', '"+sex3.getSelection().getActionCommand()+"', (select max(book_id) from book))";
                PreparedStatement ps = con.prepareStatement(query);                                
                PreparedStatement ps1 = con.prepareStatement(query2);                              
                PreparedStatement ps2 = con.prepareStatement(query3);                
                PreparedStatement ps3 = con.prepareStatement(query4);
                
                ps.execute();
                ps1.execute();
                ps2.execute();
                ps3.execute();
                
                User_Dashboard User_Dashboard = new User_Dashboard();
                User_Dashboard.setVisible(true);
                this.dispose();
            }
            catch(Exception e)
            {
                
            }
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        char c = evt.getKeyChar();
            if(Character.isLetter(c) || Character.isDigit(c)|| Character.isISOControl(c) || Character.isSpace(c) || c == KeyEvent.VK_COMMA || c == KeyEvent.VK_MINUS || c == KeyEvent.VK_QUOTE || c == KeyEvent.VK_SHIFT){
                jTextField1.setEditable(true);
                
            }else{
                jTextField1.setEditable(false);
            }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try
        {
            int pos = jTextField1.getCaretPosition();
            jTextField1.setCaretPosition(pos);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        try
        {
            int pos = jTextArea1.getCaretPosition();
            jTextArea1.setCaretPosition(pos);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_jTextArea1KeyReleased

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        User_Dashboard User_Dashboard = new User_Dashboard();
        User_Dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.ButtonGroup sex1;
    private javax.swing.ButtonGroup sex2;
    private javax.swing.ButtonGroup sex3;
    // End of variables declaration//GEN-END:variables
}
